### ISSUE TITLE
Cannot start nuxt:  Cannot read properties of undefined (reading 'push') 

### ISSUE THREAD

**Issue by PavlosMac** [wobsoriano/nuxt-proxy#14]
I am getting `Cannot start nuxt:  Cannot read properties of undefined (reading 'push') ` error with:

`nuxt 3.0.0`
`nuxt-proxy 0.3.4`

Any ideas what is going wrong?

**Comment by wobsoriano** [comment]
Not sure. Do you have a simple repro I can play with?

**Comment by wobsoriano** [comment]
Please update to latest version.
