### ISSUE TITLE
Event not working

### ISSUE THREAD

**Issue by tung1998** [wobsoriano/nuxt-proxy#15]
![image](https://user-images.githubusercontent.com/25732360/207284210-095e52f7-439e-4d59-a00e-355661f7c2b4.png)
i added "on" option but it not working

**Comment by wobsoriano** [comment]
Nuxt config accepts only JSON serializable objects. See [this](https://github.com/nuxt/framework/discussions/9551). If you want to do that, you can opt-out of the module and directly use it in a server middleware:

```ts
// server/middleware/proxy.ts

import { createProxyMiddleware } from 'nuxt-proxy/middleware';

export default createProxyMiddleware({
  target: 'https://jsonplaceholder.typicode.com',
  changeOrigin: true,
  pathRewrite: {
    '^/api/todos': '/todos',
  },
  pathFilter: ['/api/todos'],
  on: {
    proxyReq(proxyReq) {
      console.log(proxyReq)
    }
  }
});
```
