### ISSUE TITLE
Not starting after build

### ISSUE THREAD

**Issue by KhaledAlMana** [wobsoriano/nuxt-proxy#17]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.2`
- Builder:          `vite`
- User Config:      `typescript`, `ssr`, `runtimeConfig`, `app`, `css`, `modules`, `build`, `experimental`, `components`, `vite`, `intlify`, `vueuse`, `windicss`, `content`, `openidConnect`
- Runtime Modules:  `nuxt-windicss@2.6.0`, `@intlify/nuxt3@0.2.4`, `@vueuse/nuxt@9.6.0`, `@nuxt/content@2.2.0`, `@pinia/nuxt@0.4.6`, `nuxt-openid-connect@0.4.5`, `nuxt-proxy@0.3.4`, `unplugin-icons/nuxt`
- Build Modules:    `-`
------------------------------

### Reproduction 
Build and start or preview 

### Error 

```
/path/to/my/project/.output/server/node_modules/http-proxy-middleware/dist/path-rewriter.js:4
const isPlainObj = require("is-plain-obj");
                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/my/project/.output/server/node_modules/is-plain-obj/index.js from /path/to/my/project/.output/server/node_modules/http-proxy-middleware/dist/path-rewriter.js not supported.
Instead change the require of index.js in/path/to/my/project/.output/server/node_modules/http-proxy-middleware/dist/path-rewriter.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/path/to/my/project/.output/server/node_modules/http-proxy-middleware/dist/path-rewriter.js:4:20)
    at Object.<anonymous> (/path/to/my/project/.output/server/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:8:22)
    at Object.<anonymous> (/path/to/my/project/.output/server/node_modules/http-proxy-middleware/dist/index.js:18:33)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by wobsoriano** [comment]
Can you try v0.3.12?

**Comment by palexander** [comment]
I can confirm the same error with v0.3.12, but I cannot reproduce it with a toy example. Same node, nuxt, nitro versions as reported above. Also using vite. Adding these additional library and config options to the toy project does not trigger the issue. 

The error only happens when running `nuxt start` or `node .output/server/index.mjs`, using `nuxt dev` runs just fine.

Any pointers on where I should look? I'm happy to continue to investigate, but it would be nice to narrow my focus.

**Comment by wobsoriano** [comment]
Try the latest version please, thanks!

Feel free to reopen it if you still get the error.
