### ISSUE TITLE
[Feature]: Multiple Targets

### ISSUE THREAD

**Issue by Blemming** [wobsoriano/nuxt-proxy#2]
Is it possible to have multiple proxy targets using this module ?

In the nuxt 2 proxy module, the proxy option takes either an array of configs or an object.
ie:
```js
export default defineNuxtConfig({
  proxy:[
    {
      target: 'http://api1.domain.com',
      pathFilter: [
        '/api/v1/**'
      ]
    },
    {
      target: 'http://api2.domain.com',
      pathFilter: [
        '/api/v2/**'
      ]
    }
  ]
})
```

**Comment by wobsoriano** [comment]
You are right, this module only accepts a single target. I’ll add that feature.

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/nuxt-proxy/releases/tag/v0.2.0
