### ISSUE TITLE
Release 0.2.1 appears to no longer function

### ISSUE THREAD

**Issue by andrew-teirney** [wobsoriano/nuxt-proxy#4]
I just recently upgraded to 0.2.1 and it appears to no longer function. I suspect a packaging issue.

When running `nuxi dev` I get the following error.

```
 ERROR  Cannot start nuxt:  Cannot find module '/Users/wobsoriano/tmp/nuxt-proxy/src/module'
```

It appears as though this path is referenced in the `dist/module.mjs` file, the content of which is.

```
import jiti from 'jiti';
export default jiti(null, { interopDefault: true })('/Users/wobsoriano/tmp/nuxt-proxy/src/module');
```

**Comment by wobsoriano** [comment]
Thanks for reporting! Can you try v0.2.3 now? Thanks!

**Comment by andrew-teirney** [comment]
Looks to be all good now. Appreciate the prompt fix.
