### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by wvffle** [wobsoriano/nuxt-proxy#5]
Could you please add websocket support?

**Comment by asonnleitner** [comment]
@wvffle websockets should be available out of the box, just set `ws: true` in the proxy options. 

https://github.com/chimurai/http-proxy-middleware#websocket

**Comment by jonkri** [comment]
Should this work?

```
$ cat server/middleware/proxy.ts
import { createProxyMiddleware } from 'nuxt-proxy/middleware'

export default createProxyMiddleware({
  changeOrigin: true,
  pathFilter: '/raw',
  pathRewrite: { '^/raw': '' },
  target: 'https://ws.postman-echo.com/raw',
  ws: true
})
```

This command just hangs:

```
$ echo "test" | websocat ws://localhost:3000/raw
```

This command works:

```
$ echo "test" | websocat wss://ws.postman-echo.com/raw
test
```

**Comment by iamsurelydaveydave** [comment]
proxy: {
    options: [
      {
        target: process.env.AUTHENTICATION_API,
        changeOrigin: true,
        pathRewrite: {
          "^/api/auth": "/api",
          "^/api/organizations": "/api/organizations",
        },
        pathFilter: ["/api/auth", "/api/organizations"],
      },
      {
        target: process.env.AUTHENTICATION_API,
        changeOrigin: true,
        pathFilter: ["/socket.io"],
        ws: true,
      },
    ],
  },
  
  unction connectToOrganizationNamespace() {
    const socket = io("/organizations", {
      transports: ["websocket"],
    });
    socket.on("connect", () => {
      console.log("connected to /organization namespace");
    });
    socket.on("disconnect", () => {
      console.log("disconnected from /organization namespace");
    });
    return socket;
  }
  
  it's not working

**Comment by iamsurelydaveydave** [comment]
> proxy: { options: [ { target: process.env.AUTHENTICATION_API, changeOrigin: true, pathRewrite: { "^/api/auth": "/api", "^/api/organizations": "/api/organizations", }, pathFilter: ["/api/auth", "/api/organizations"], }, { target: process.env.AUTHENTICATION_API, changeOrigin: true, pathFilter: ["/socket.io"], ws: true, }, ], },
> 
> unction connectToOrganizationNamespace() { const socket = io("/organizations", { transports: ["websocket"], }); socket.on("connect", () => { console.log("connected to /organization namespace"); }); socket.on("disconnect", () => { console.log("disconnected from /organization namespace"); }); return socket; }
> 
> it's not working

or I'm I doing it wrong?
