### ISSUE TITLE
Inject target from env at runtime instead of build time

### ISSUE THREAD

**Issue by marssantoso** [wobsoriano/nuxt-proxy#9]
As titled. Is it possible to inject the target value from environment variables at runtime instead of build time?

Using this option:

```ts
  proxy: {
    options: [
      {
        target: process.env.API_HOST,
        changeOrigin: true,
        pathRewrite: {
          '^/api/': '',
        },
        pathFilter: ['/api/'],
      },
    ],
  },
```

It's working fine when supplying the `API_HOST` value in the `.env` and bulid it, then run it. However, removing it from `.env` and supplying at runtime yields in this error:

```sh
Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}
```

Edit: this issue especially occurs in production environment

**Comment by wobsoriano** [comment]
Feel free to reopen.

**Comment by vaschindler** [comment]
@wobsoriano  This still does not work for me. I have a proxy with a target like above defined and when I build locally the target can be injected from environment variables. In my setup I am building the project in a pipeline and deploy it with kubernetes, which should inject the env  NUXT_TEST at runtime. This is not working and I am not sure how to fix it. Am I missing something?

```
 runtimeConfig: {
    proxy: {
      options: [
        {
          pathFilter: ['/api/test'],
          target: process.env.NUXT_TEST,
          changeOrigin: true,
          pathRewrite: {
            '^/api/test':  ''
          }
        }
      ]
    }
  },
```
